{% set name = "neo4jsbml" %}
{% set version = "0.12.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/{{ name }}/archive/{{ version }}.tar.gz
  sha256: f198da064a55d9874451c9e6d3e38f550c883e704bd33323326ec4e49d46e442

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .
  entry_points:
    - neo4jsbml=neo4jsbml.__main__:main

requirements:
  host:
    - python >=3.8
    - pip
    - pyyaml
    - setuptools
  run:
    - python >=3.8
    - python-libsbml
    - neo4j-python-driver
    - networkx
    - sphinx
    - sphinx_rtd_theme

test:
  imports:
    - {{ name }}
  commands:
    - {{ name }} --help

about:
  home: https://github.com/brsynth/neo4jsbml
  summary: Import SBML file into Neo4j
  license: MIT
  license_file: LICENSE
  doc_url: https://neo4jsbml.readthedocs.io/
  dev_url: https://github.com/brsynth/neo4jsbml

extra:
  recipe-maintainers:
    - guillaume-gricourt
    - tduigou
